In [2]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('data.csv')
data.iloc[:10]

                  nom   matiere  note
0    Laurent Dagenais  Français    16
1          Guy Marois  Français    13
2     Beaufort Lesage  Français     8
3      Russell Durand  Français    10
4         Alexis Riel  Français    15
5       Leon Lapresse  Français    17
6    Orville Routhier  Français     6
7      Agramant Pepin  Français    17
8  Aiglentina Lambert  Français    16
9     Theodore Clavet  Français     8

In [16]:
moyenne = round(data[data['matiere'] == 'Mathématiques']['note'].mean(), 2)
print(moyenne)

11.33

In [22]:
moyenne_par_eleve = data.groupby('nom')['note'].mean()
eleves_pas_moyenne = moyenne_par_eleve[moyenne_par_eleve < 10]
print(eleves_pas_moyenne)

nom
Aiglentina Lambert    8.50
Alexis Riel           9.00
Amaury Reault         8.50
Orville Routhier      8.25
Russell Durand        8.50
Theodore Clavet       9.50
Name: note, dtype: float64

In [26]:
notes = data.loc[((data['matiere'] == 'Mathématiques') | (data['matiere'] == 'Physique/Chimie')) & (data['note'] >= 15), ['nom','matiere','note']]
notes

                nom          matiere  note
22       Guy Marois    Mathématiques    17
23  Beaufort Lesage    Mathématiques    15
28   Agramant Pepin    Mathématiques    18
30  Theodore Clavet    Mathématiques    16
31   Byron Lefebvre    Mathématiques    19
32     Florus Devoe    Mathématiques    19
65  Beaufort Lesage  Physique/Chimie    18
68    Leon Lapresse  Physique/Chimie    17
70   Agramant Pepin  Physique/Chimie    16
74     Florus Devoe  Physique/Chimie    15
78  Agate Grandbois  Physique/Chimie    17
81   Yseult Charest  Physique/Chimie    16
82   Dorothee Aupry  Physique/Chimie    17