## Personnes

In [1]:
# import des librairies dont nous aurons besoin
import pandas as pd
import numpy as np
import re

In [2]:
data = pd.read_csv('personnes.csv')
data

,prenom,email,date_naissance,pays,taille
0,Leila,leila@example.com,23/01/1990,France,1.49m
1,Samuel,samuel_329@example.com,20/09/2001,NaN,1.67m
2,Radia,choupipoune@supermail.eu,12 sept. 1984,Côte d'ivoire,153cm
3,Marc,"marco23@example.com, mc23@supermail.eu",10/02/1978,France,1.65m
4,Heri,helloworld@supermail.eu,05/03/2008,Madagascar,1.34m
5,Hanna,hanna2019@supermail.eu,01/01/1970,24,3.45m
6,samuël,samuel_329@example.com,NaN,Bénin,1.45m

## Detectez les erreurs
### Erreur manquante

In [3]:
data.isnull().sum()

prenom            0
email             0
date_naissance    1
pays              1
taille            0
dtype: int64

### Erreur doublon

In [4]:
data.loc[data['email'].duplicated(keep=False),:]

   prenom                   email date_naissance   pays taille
1  Samuel  samuel_329@example.com     20/09/2001    NaN  1.67m
6  samuël  samuel_329@example.com            NaN  Bénin  1.45m

### Traitez les erreurs

In [ ]:
data['nom_colonne'] = nouvelle_colonne

#### Traitez les pays

In [15]:
VALID_COUNTRIES = ['France', 'Côte d\'ivoire', 'Madagascar', 'Bénin', 'Allemagne'
                  , 'USA']
mask = ~data['pays'].isin(VALID_COUNTRIES)
data.loc[mask, 'pays'] = np.nan

#### Traitez les e-mails

In [ ]:
data['email'] = data['email'].str.split(',', n=1, expand=True)[0]

#### Traitez les tailles

In [17]:
data['taille'] = data['taille'].str[:-1]
data['taille'] = pd.to_numeric(data['taille'], errors='coerce')

In [ ]:
data.loc[data['taille'].isnull(), 'taille'] = data['taille'].mean()

#### Traitez les dates

In [19]:
data['date_naissance'] = pd.to_datetime(data['date_naissance'], 
                                           format='%d/%m/%Y', errors='coerce')
data

   prenom                     email date_naissance pays    taille
0   Leila         leila@example.com     1990-01-23  NaN  1.490000
1  Samuel    samuel_329@example.com     2001-09-20  NaN  1.670000
2   Radia  choupipoune@supermail.eu            NaT  NaN  1.841667
3    Marc       marco23@example.com     1978-02-10  NaN  1.650000
4    Heri   helloworld@supermail.eu     2008-03-05  NaN  1.340000
5   Hanna    hanna2019@supermail.eu     1970-01-01  NaN  3.450000
6  samuël    samuel_329@example.com            NaT  NaN  1.450000