In [1]:
import pandas as pd

In [8]:
commandes = pd.read_csv('commande.csv')
commandes.head()

   id  nombre
0  70       2
1  41       4
2  72       2
3  92       8
4  73       1

In [7]:
produits = pd.read_csv('produits.csv')
produits.head()

   id  prix
0   0  24.8
1   1  13.1
2   2  23.7
3   3  16.0
4   4  19.0

In [12]:
data = pd.merge(commandes,produits, on='id', how='left')
data.head()

   id  nombre  prix
0  70       2  17.6
1  41       4  20.7
2  72       2  14.9
3  92       8   7.4
4  73       1  22.5

In [19]:
produit_plus_vendu = commandes.groupby('id')['nombre'].sum().idxmax()
produit_plus_vendu

np.int64(8)

In [28]:
data['CA'] = data['nombre'] * data['prix']
data['CA'].min()

np.float64(5.8)